### ISSUE TITLE
[main] Switch to a context-based configuration

### ISSUE THREAD

**Issue by drf** [astarte-platform/astartectl#80]
## Rationale
Currently, astartectl requires a tedious process of setting URLs/configuration flags everytime, or a configuration file mechanism which is not widely used due to the tedious process of setting it up.

## Solution
Switch to a kubectl-like context mechanism, which allows for multiple configuration switching at runtime and easy loading of different cluster/realm configuration.

## Tasks
- [x] Create a base structure for context-based configuration. Take something like https://github.com/fnproject/cli/tree/master/config as inspiration
  * [x] Rather than having a huge YAML file such as kubectl, keep a clusters/ and contexts/ directory and single yaml files for each of them (Cluster == astarte cluster, Context == Astarte Cluster+Astarte Realm)
  * [x] Create a YAML struct to ensure we can validate contexts easily and import/export them properly
- [x] Add environment variables/config switches to allow replacing current context
  * [x] `--context`, `ASTARTE_CONTEXT` to switch current context
  * [x] `--config-dir`, `ASTARTE_CONFIG_DIR` to use custom configuration directory
- [x] Port existing configuration to use the new structure
- [x] `astartectl housekeeping realm create` should automatically create a context entry in astartectl config
- [x] `astartectl cluster deploy` should automatically create a cluster entry in astartectl config
- [x] `astartectl cluster get-cluster-config`, to fetch cluster configuration from the current kubectl context
- [x] Allow for `astartectl config import` and `astartectl config export` to bundle configuration into a single YAML file to pass it around easily
- [x] `astartectl config {get,set,rename,delete}-{context,cluster}`, `astartectl config use-context`, kubectl-style, to define default cluster and context for interaction
